sudo: required
services:
  - docker

before_install:
  - docker build -t dollypizzle/birdboard-test -f Dockerfile .
script:
  - docker run dollypizzle/birdboard-test vendor/bin/phpunit

after_success:
  - docker build -t dollypizzle/birdboard-app .
  - docker build -t dollypizzle/birdboard-nginx -f Dockerfile.nginx .
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push dollypizzle/birdboard-app
  - docker push dollypizzle/birdboard-nginx

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: birdboard-aws
  env: BirdboardAws-env
  bucket_name: elasticbeanstalk-ap-southeast-2-092749212479
  bucket_path: birdboard-cli
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
