FROM php:7.2-fpm

RUN apt-get update \
    && apt-get -y install git zip unzip default-mysql-client nginx \
    libmcrypt-dev libmagickwand-dev --no-install-recommends \
    && pecl install mcrypt-1.0.2 \
    && docker-php-ext-install pdo_mysql zip \
    && docker-php-ext-enable mcrypt

WORKDIR /var/www

COPY composer.lock composer.json ./
COPY database ./database

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && php composer.phar install --no-scripts \
    && rm composer.phar

COPY default.conf /etc/nginx/sites-enabled/default

COPY . .

RUN cp .env.example .env && php artisan key:generate

RUN chown -R $USER:www-data storage
RUN chown -R $USER:www-data bootstrap/cache
RUN chmod -R 775 storage
RUN chmod -R 775 bootstrap/cache

CMD ["bash", "start.sh"]
